# Generated by Django 3.2.6 on 2021-08-13 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0002_certificate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['name2'], 'verbose_name_plural': 'certificates'},
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='created_at',
            new_name='created_at2',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='desc',
            new_name='desc2',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='image',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='name',
            new_name='name2',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='created_by',
        ),
        migrations.AddField(
            model_name='certificate',
            name='created_by2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to=settings.AUTH_USER_MODEL),
        ),
    ]
