# Generated by Django 3.2.6 on 2021-08-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
